# Site settings
title: Decred Arabic
description: A blog about reports and articles about Decred in Arabic
baseurl: "/decred-arabic/" # the subpath of your site, e.g. /blog
url: "https://insaf01.github.io/decred-arabic/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Decred Arabic
user_description: Decred Articles in arabic


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
